import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({ 
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: 'SITENAME_TOKEN',
  description: 'Generated by SITENAME_TOKEN',
  icons: {
    icon: 'ICON_TOKEN',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <nav className="bg-white shadow-lg border-b border-primary/20">
          <div className="container mx-auto px-4">
            <div className="flex justify-between items-center h-16">
              <div className="flex items-center space-x-2">
                <div className="w-8 h-8 bg-primary rounded-full"></div>
                <h1 className="text-xl font-bold text-gray-800">SITENAME_TOKEN</h1>
              </div>
              <div className="hidden md:flex space-x-8">
                <a href="/home" className="text-gray-600 hover:text-primary transition-colors border-b-2 border-transparent hover:border-primary py-4">
                  Home
                </a>
                <a href="/product" className="text-gray-600 hover:text-primary transition-colors border-b-2 border-transparent hover:border-primary py-4">
                  Product
                </a>
                <a href="/about" className="text-gray-600 hover:text-primary transition-colors border-b-2 border-transparent hover:border-primary py-4">
                  About
                </a>
              </div>
              <button className="bg-primary text-white px-4 py-2 rounded-md hover:bg-primary/90 transition-colors">
                Contact
              </button>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
