import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SITENAME_TOKEN',
  description: 'Generated by SITENAME_TOKEN',
  icons: {
    icon: 'ICON_TOKEN',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-primary text-white p-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">SITENAME_TOKEN</h1>
            <div className="space-x-4">
              <a href="/home" className="hover:text-secondary">Home</a>
              <a href="/product" className="hover:text-secondary">Product</a>
              <a href="/about" className="hover:text-secondary">About</a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
